#!/bin/sh
 . "$(dirname "$0")/_/husky.sh"

if [ "$excludeAddon" != "cosi" ]; then
  npm run prePushHook
fi
if [ "$excludeAddon" = "cosi" ]; then
  echo "run prepush hook without $excludeAddon"
  npm run prePushHookExcludeAddon
fi